In [4]:
import pandas as pd
df = pd.concat(
    map(pd.read_csv, ['/kaggle/input/canadian-fuel-consumption-ratings/MY2015 Fuel Consumption Ratings.csv', '/kaggle/input/canadian-fuel-consumption-ratings/MY2016 Fuel Consumption Ratings.csv']), ignore_index=True)
df.describe()

,Engine Size (L),Cylinders,Fuel Consumption (City) (L/100 km),Fuel Consumption (Hwy) (L/100 km),Fuel Consumption (Comb) (L/100 km),Fuel Consumption (Comb) (mpg),CO2 Emissions (g/km),CO2 Rating,Smog Rating
count,2242.000000,2242.000000,2242.000000,2242.000000,2242.000000,2242.000000,2242.000000,1110.000000,0.0
mean,3.145450,5.570919,12.538582,8.886084,10.895406,27.607939,247.561552,5.211712,NaN
std,1.336405,1.788358,3.448738,2.162785,2.839039,6.966433,57.372313,1.531529,NaN
min,0.900000,3.000000,4.400000,4.600000,4.500000,11.000000,104.000000,1.000000,NaN
25%,2.000000,4.000000,10.000000,7.300000,8.800000,23.000000,205.000000,4.000000,NaN
50%,3.000000,6.000000,12.100000,8.600000,10.500000,27.000000,242.000000,5.000000,NaN
75%,3.700000,6.000000,14.600000,10.000000,12.500000,32.000000,283.000000,6.000000,NaN
max,8.400000,12.000000,30.600000,20.600000,26.100000,63.000000,476.000000,10.000000,NaN

In [5]:
df.head(10)

,Year,Make,Model,Vehicle Class,Engine Size (L),Cylinders,Transmission,Fuel Type,Fuel Consumption (City) (L/100 km),Fuel Consumption (Hwy) (L/100 km),Fuel Consumption (Comb) (L/100 km),Fuel Consumption (Comb) (mpg),CO2 Emissions (g/km),CO2 Rating,Smog Rating
0,2015,ACURA,ILX,COMPACT,2.0,4.0,AS5,Z,9.7,6.7,8.3,34.0,191.0,NaN,NaN
1,2015,ACURA,ILX,COMPACT,2.4,4.0,M6,Z,10.8,7.4,9.3,30.0,214.0,NaN,NaN
2,2015,ACURA,ILX HYBRID,COMPACT,1.5,4.0,AV7,Z,6.0,6.1,6.1,46.0,140.0,NaN,NaN
3,2015,ACURA,MDX SH-AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.7,9.1,11.1,25.0,255.0,NaN,NaN
4,2015,ACURA,RDX AWD,SUV - SMALL,3.5,6.0,AS6,Z,12.1,8.7,10.6,27.0,244.0,NaN,NaN
5,2015,ACURA,RLX,MID-SIZE,3.5,6.0,AS6,Z,11.9,7.7,10.0,28.0,230.0,NaN,NaN
6,2015,ACURA,RLX HYBRID,MID-SIZE,3.5,6.0,AM7,Z,8.0,7.5,7.7,37.0,177.0,NaN,NaN
7,2015,ACURA,TLX,COMPACT,2.4,4.0,AM8,Z,9.6,6.6,8.3,34.0,191.0,NaN,NaN
8,2015,ACURA,TLX,COMPACT,3.5,6.0,AS9,Z,11.2,6.9,9.2,31.0,212.0,NaN,NaN
9,2015,ACURA,TLX SH-AWD,COMPACT,3.5,6.0,AS9,Z,11.2,7.5,9.6,29.0,221.0,NaN,NaN

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Year                                2260 non-null   object
 1   Make                                2277 non-null   object
 2   Model                               2242 non-null   object
 3   Vehicle Class                       2242 non-null   object
 4   Engine Size (L)                     2242 non-null   float64
 5   Cylinders                           2242 non-null   float64
 6   Transmission                        2242 non-null   object
 7   Fuel Type                           2242 non-null   object
 8   Fuel Consumption (City) (L/100 km)  2242 non-null   float64
 9   Fuel Consumption (Hwy) (L/100 km)   2242 non-null   float64
 10  Fuel Consumption (Comb) (L/100 km)  2242 non-null   float64
 11  Fuel Consumption (Comb) (mpg)       2242 non-null   float64
 12  CO2 Emissions (g/km)                2242 non-null   float64
 13  CO2 Rating                          1110 non-null   float64
 14  Smog Rating                         0 non-null      float64
dtypes: float64(9), object(6)
memory usage: 268.5+ KB

In [41]:
from tabulate import tabulate
dictBaru = {
    "banyak record" : [len(df)],
    "banyak atribute" : [len(df.columns)],
    "nama atribute" : ["\n".join(list(df.columns))],
    "banyak atribut angka" : [len(df.dtypes[df.dtypes == "float64"])],
}

print(tabulate(pd.DataFrame(dictBaru), headers="keys", tablefmt="psql", showindex=False))

+-----------------+-------------------+------------------------------------+------------------------+
|   banyak record |   banyak atribute | nama atribute                      |   banyak atribut angka |
|-----------------+-------------------+------------------------------------+------------------------|
|            2290 |                15 | Year                               |                      9 |
|                 |                   | Make                               |                        |
|                 |                   | Model                              |                        |
|                 |                   | Vehicle Class                      |                        |
|                 |                   | Engine Size (L)                    |                        |
|                 |                   | Cylinders                          |                        |
|                 |                   | Transmission                       |                        |
|                 |                   | Fuel Type                          |                        |
|                 |                   | Fuel Consumption (City) (L/100 km) |                        |
|                 |                   | Fuel Consumption (Hwy) (L/100 km)  |                        |
|                 |                   | Fuel Consumption (Comb) (L/100 km) |                        |
|                 |                   | Fuel Consumption (Comb) (mpg)      |                        |
|                 |                   | CO2 Emissions (g/km)               |                        |
|                 |                   | CO2 Rating                         |                        |
|                 |                   | Smog Rating                        |                        |
+-----------------+-------------------+------------------------------------+------------------------+

In [49]:
df.loc[94:len(df), "Engine Size (L)":"Smog Rating"]

,Engine Size (L),Cylinders,Transmission,Fuel Type,Fuel Consumption (City) (L/100 km),Fuel Consumption (Hwy) (L/100 km),Fuel Consumption (Comb) (L/100 km),Fuel Consumption (Comb) (mpg),CO2 Emissions (g/km),CO2 Rating,Smog Rating
94,2.0,4.0,AS8,D,7.6,5.5,6.7,42.0,181.0,NaN,NaN
95,2.0,4.0,AS8,Z,10.0,6.5,8.4,34.0,193.0,NaN,NaN
96,2.0,4.0,M6,Z,10.7,6.9,9.0,31.0,207.0,NaN,NaN
97,2.0,4.0,AS8,Z,10.6,7.2,9.1,31.0,209.0,NaN,NaN
98,2.0,4.0,AS8,Z,10.6,7.2,9.1,31.0,209.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.iloc[94:len(df), 4:15]

,Engine Size (L),Cylinders,Transmission,Fuel Type,Fuel Consumption (City) (L/100 km),Fuel Consumption (Hwy) (L/100 km),Fuel Consumption (Comb) (L/100 km),Fuel Consumption (Comb) (mpg),CO2 Emissions (g/km),CO2 Rating,Smog Rating
94,2.0,4.0,AS8,D,7.6,5.5,6.7,42.0,181.0,NaN,NaN
95,2.0,4.0,AS8,Z,10.0,6.5,8.4,34.0,193.0,NaN,NaN
96,2.0,4.0,M6,Z,10.7,6.9,9.0,31.0,207.0,NaN,NaN
97,2.0,4.0,AS8,Z,10.6,7.2,9.1,31.0,209.0,NaN,NaN
98,2.0,4.0,AS8,Z,10.6,7.2,9.1,31.0,209.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
ok = 0
for i in list(df.columns[df.dtypes == "object"]):
    ok = ok + df[i].notnull().sum()
    
print(ok)

13505